routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    return view('admin.home');
})->name('home');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // return view('welcome');
//     return view('admin.login');
// });

Route::get('/', 'App\Http\Controllers\Auth\LoginController@showLoginForm');

Auth::routes();

Route::post('/login', 'App\Http\Controllers\Auth\LoginController@login');

// Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

Route::get('/merchants', 'App\Http\Controllers\Resource\MerchantResource@index');

Route::resource('category', 'App\Http\Controllers\Resource\CategoryResource');

Route::resource('business-type', 'App\Http\Controllers\Resource\BusinessTypeResource');

Route::resource('business-document', 'App\Http\Controllers\Resource\BusinessDocumentResource');

Route::resource('role', 'App\Http\Controllers\Resource\RoleResource');

resources/views/admin/business-type/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="dashboard-content-bdy p-3">
    <div class="card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap">
        <h3 class="fw-bold mb-0">Create Business Type</h3>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="payout-data">
                <div class="card mb-3">
                    <div class="card-body">
                        <form id="basic-form" method="post" action="{{route('business-type.store')}}" novalidate="">
                            @csrf
                            <div class="row g-3 align-items-center">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">Name</label>
                                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}" required>
                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/business-type/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="dashboard-content-bdy p-3">
    <div class="card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap">
        <h3 class="fw-bold mb-0">Edit Business Type</h3>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="payout-data">
                <div class="card mb-3">
                    <div class="card-body">
                        <form id="basic-form" method="post" action="{{route('business-type.update', $businessType->id)}}" novalidate="">
                            @csrf
                            @method('PATCH')
                            <div class="row g-3 align-items-center">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">Name</label>
                                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$businessType->name}}" required>
                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/business-type/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="dashboard-content-bdy p-3">
    <div class="card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap">
        <h3 class="fw-bold mb-0">Business Type</h3>
        <div class="col-auto d-flex w-sm-100">
        <a href="{{route('business-type.create')}}" class="btn btn-primary btn-set-task w-sm-100" data-bs-toggle="modal" data-bs-target="#sendsheet">Create</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="payout-data">
                <table id="example" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($businessTypes as $index => $businessType)
                        <tr>
                            <td>{{$index+1}}</td>
                            <td>{{$businessType->name}}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn  merchant-action dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-h"></i>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a href="{{route('business-type.edit', $businessType->id)}}" class="dropdown-item">Edit</a>
                                        <a href="#" class="dropdown-item" onClick="event.preventDefault(); if(confirm('Are you sure want to delete?')) { document.getElementById('business-type-delete-{{$businessType->id}}').submit();}" class="btn btn-outline-secondary deleterow">Delete</a>
                                        <form id="business-type-delete-{{$businessType->id}}" action="{{ route('business-type.destroy', $businessType->id) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="3"><p class="text-center">No results found.</p></td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>S/N</th>
                            <th>Name</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                </table>
                {!!$businessTypes->render()!!}
            </div>
            <hr>
        </div>
    </div>
</div>

@endsection

@section('style')

<link rel="stylesheet" type="text/css" href="/assets/css/datatable.css">

@endsection

@section('script')

<script type="text/javascript" src="/assets/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/js/dataTables.bootstrap4.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
} );
</script>

@endsection