routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    return view('admin.home');
})->name('home');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // return view('welcome');
//     return view('admin.login');
// });

Route::get('/', 'App\Http\Controllers\Auth\LoginController@showLoginForm');

Auth::routes();

Route::post('/login', 'App\Http\Controllers\Auth\LoginController@login');

// Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

Route::get('/merchants', 'App\Http\Controllers\Resource\MerchantResource@index');

Route::resource('category', 'App\Http\Controllers\Resource\CategoryResource');

Route::resource('business-type', 'App\Http\Controllers\Resource\BusinessTypeResource');

Route::resource('business-document', 'App\Http\Controllers\Resource\BusinessDocumentResource');

Route::resource('role', 'App\Http\Controllers\Resource\RoleResource');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Payvettar Admin</title>

    <!-- Bootstrap CSS CDN -->
     <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="/assets/css/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/admin.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/responsive.css">
    <!-- Font Awesome JS -->
    @yield('style')
</head>
<body>
    <div class="wrapper">
        @include('admin.layouts.sidebar')

        <!-- Page Content  -->
        <div id="content">
            @include('admin.layouts.navbar')
            @yield('content')
        </div>

    </div>

<script src="/assets/js/jquery.min.js"></script>
  <script src="/assets/js/popper.min.js"></script>
  <script src="/assets/js/bootstrap.min.js"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="/assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="/assets/js/Chart.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function()
            {
                $('.toggle-btn span').click(function()
                    {
                        $(this).siblings().removeClass('t-active');
                        $(this).addClass('t-active');
                    });
            });
    </script>

    @yield('script')
    
</body>

</html>

resources/views/admin/layouts/auth.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Payvettar Admin</title>

    <!-- Bootstrap CSS CDN -->
     <link rel="stylesheet" href="/assets/admin/css/bootstrap.min.css">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="/assets/admin/css/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" type="text/css" href="/assets/admin/css/style.css">
    <link rel="stylesheet" type="text/css" href="/assets/admin/css/admin.css">
    <link rel="stylesheet" type="text/css" href="/assets/admin/css/responsive.css">
    <!-- Font Awesome JS -->
  

</head>
<body>

@yield('content')

<script src="/assets/admin/js/jquery.min.js"></script>
  <script src="/assets/admin/js/popper.min.js"></script>
  <script src="/assets/admin/js/bootstrap.min.js"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="/assets/admin/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="/assets/admin/js/Chart.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function()
            {
                $('.toggle-btn span').click(function()
                    {
                        $(this).siblings().removeClass('t-active');
                        $(this).addClass('t-active');
                    });
            });
    </script>

    @yield('script')
    
</body>

</html>

resources/views/admin/layouts/navbar.blade.php
<div class="top-sec">
              <div class="row align-items-center">
                  <div class="col-md-4">
                      <div class="page-title">
                          <h1></h1>
                      </div>
                       <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                  </div>
                  <div class="col-md-8">
                      <div class="right-mnu ">
                          <ul class="d-flex justify-content-end align-items-center">
                              {{--<li>
                                  <div class="toggle-btn">
                                      <span class="t-active">Test</span>
                                      <span>Live</span>
                                  </div>
                              </li>--}}
                              <li>
                                  <div class="profile-show">
                                    <div class="d-flex align-items-center">
                                      <div class="profile-img"><img src="/assets/images/profile-img.png"></div>
                                      <div class="user-name">
                                          <h4>{{Auth::user()->name}}</h4>
                                          <p>Admin</p>
                                      </div>
                                      <div class="select-drop">
                                          <div class="dropdown">
                                          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                            <i class="fal fa-chevron-down"></i>
                                          </button>
                                          <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                                @csrf
                                            </form>
                                          </div>
                                        </div>
                                      </div>
                                  </div>
                                  </div>
                              </li>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>  

resources/views/admin/layouts/sidebar.blade.php
<nav id="sidebar">
    <div class="sidebar-header admin-logo">
        <img src="/assets/images/logo.png">
    </div>

    <ul class="list-unstyled components">
      
        <li>
            <a href="#">Dashboard</a>
        </li>
        <li class="{{(Request::segment('1') == 'merchants') ? 'active' : ''}}">
            <a href="{{url('merchants')}}">Merchant</a>
        </li>
        <li class="{{(Request::segment('1') == 'category') ? 'active' : ''}}">
            <a href="{{route('category.index')}}">Category</a>
        </li>
        <li class="{{(Request::segment('1') == 'business-type') ? 'active' : ''}}">
            <a href="{{route('business-type.index')}}">Business Type</a>
        </li>
        <li class="{{(Request::segment('1') == 'business-document') ? 'active' : ''}}">
            <a href="{{route('business-document.index')}}">Business Document</a>
        </li>
        <li class="{{(Request::segment('1') == 'role') ? 'active' : ''}}">
            <a href="{{route('role.index')}}">Role</a>
        </li>
        <li>
            <a href="#">Transactions</a>
        </li>
        <li><a href="#">API Analytics</a></li>
        <li><a href="#">Reports</a></li>
    </ul>
</nav>